### ISSUE TITLE
5.15 patches - don't apply cleanly on point releases

### ISSUE THREAD

**Issue by xback** [telit/mhi-linux-kernel-patches#27]
Hi,

I'm playing around with these using 5.15 on OpenWRT.
It looks like these patches don't apply cleanly anymore on point releases (like 5.15.31)

For the time being i've altered them locally.

- Will these be updated so they follow point releases?
- Will they be upstreamed? (I can assist here if needed)

Thanks,

Koen

**Comment by xback** [comment]
Hi Daniele,
Thanks for the detailed feedback, really appreciated!

> Unfortunately we don't have enough resources to follow all stable branches and releases. We could, however, work on specific releases if needed.

I think that upgrading the patchset to stables once every 30 .. 40 releases would be more than sufficient.
If the changes are small , they could even be delivered via pull request from the community, which would lower the burden for you guys.
Also, MHI changes are near-to-none in the last 15 service releases.

This would allow easy integration within OpenWRT which should broaden the audience.

> Upstreaming would be ideal and we would really prefer that option: we are planning to do that for the standard devices (e.g. rmnet, mbim, diag) on FN980 and FN990.

I think that if all typical features would be upstreamed which are mostly-used (control, data, nmea) that more than 95% of all use-cases would already be covered.

coredumps and extended diagnostics looks like niche from the typical uses point of view. (please correct me if I'm wrong here)

Looking at the patches themselves, the basics (Ctrl, data, nmea) look trivial enough to upstream them without too much hassle.

Thanks again,

Koen

**Comment by danielepa-telit** [comment]
Hi Koen,

> Hi Daniele, Thanks for the detailed feedback, really appreciated!
> 
> > Unfortunately we don't have enough resources to follow all stable branches and releases. We could, however, work on specific releases if needed.
> 
> I think that upgrading the patchset to stables once every 30 .. 40 releases would be more than sufficient. If the changes are small , they could even be delivered via pull request from the community, which would lower the burden for you guys. Also, MHI changes are near-to-none in the last 15 service releases.
> 
> This would allow easy integration within OpenWRT which should broaden the audience.
>

I think this is something we can do: we are discussing internally the guiding principles for the upgrades to stables.

> > Upstreaming would be ideal and we would really prefer that option: we are planning to do that for the standard devices (e.g. rmnet, mbim, diag) on FN980 and FN990.
> 
> I think that if all typical features would be upstreamed which are mostly-used (control, data, nmea) that more than 95% of all use-cases would already be covered.
> 
> coredumps and extended diagnostics looks like niche from the typical uses point of view. (please correct me if I'm wrong here)
> 

Yes, that's correct. Unfortunately not the same for firmware upgrade, but we are also looking for different kind of solutions about that.

> Looking at the patches themselves, the basics (Ctrl, data, nmea) look trivial enough to upstream them without too much hassle.
>

Yes, I agree: we hope to submit the basic support for upstream soon.

Thanks for your good feedback!

> Thanks again,
> 
> Koen

**Comment by danielepa-telit** [comment]
We pushed a few branches for stable, it should now be all up-to-date.

Thanks,
Daniele

**Comment by xback** [comment]
Thanks!
Really appreciated
