### ISSUE TITLE
Patch request for kernel 6.8

### ISSUE THREAD

**Issue by mageshgv** [telit/mhi-linux-kernel-patches#57]
Hi,

With the ubuntu 24.04 close to release, it would be great if you could create patch file for kernel version 6.8.

Also, I have two questions:

* I am looking for a fix for modem not initializing after a reset(rarely) or firmware switch(always ?) (FN990A28 PCIE). From what I see patches 0004 and 0009 seem to be the relevant one, may be 0003 as well ? Is there any other patch required for stable functioning of the modem ?
* Will any of the patches cause an issue if the patched drivers are used with a PCIE 5G modem from a different vendor ? We are trying to avoid having to build different OS images for different hardware combinations. So it would be great if these patches will not interfere with other PCIE 5G modems using mhi.

Thanks.

**Comment by danielepa-telit** [comment]
Hi,


> With the ubuntu 24.04 close to release, it would be great if you could create patch file for kernel version 6.8.

This is something we will do, but at the moment no ETA. If you have an ongoing business with Telit I suggest to forward this request to your Telit point of contact.

> * I am looking for a fix for modem not initializing after a reset(rarely) or firmware switch(always ?) (FN990A28 PCIE). From what I see patches 0004 and 0009 seem to be the relevant one, may be 0003 as well ?

0003 and 0004 are needed for supporting Telit custom firmware update application, 0009 is probably what you need for the described issue.

> Is there any other patch required for stable functioning of the modem ?

Not for stability.

> * Will any of the patches cause an issue if the patched drivers are used with a PCIE 5G modem from a different vendor ? We are trying to avoid having to build different OS images for different hardware combinations. So it would be great if these patches will not interfere with other PCIE 5G modems using mhi.

Some patches could have effects also with other modems (e.g. 0001, 0009), but they should not create any issue. Anyway, we can't guarantee that.

**Comment by mageshgv** [comment]
Thanks for the detailed reply. I will close this issue.
